brew install sdl12-compat
brew install sdl2
brew install sdl2_gfx
brew install sdl2_image
brew install sdl2_mixer
brew install sdl2_net
brew install sdl2_sound
brew install sdl2_ttf
brew install sdl_gfx
brew install sdl_image
brew install sdl_mixer
brew install sdl_net
brew install sdl_rtf
brew install sdl_sound
brew install sdl_ttf
brew install scons
brew install mc
brew install vim
brew install burn
brew install macs-fan-control
brew install xemu
brew install midnight-commander
brew install wget
brew install rar
brew install openemu
brew install fs-uae-launcher
brew install git
brew install sublime
brew install sublime-text
brew install sublime-text2
brew install visual-studio-code
brew install paintbrush
brew install tiled

